# Generated by Django 4.1 on 2023-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('log_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('experience', models.CharField(default=None, max_length=100, null=True)),
                ('skills', models.CharField(default=None, max_length=100, null=True)),
                ('basic_edu', models.CharField(default=None, max_length=100, null=True)),
                ('master_edu', models.CharField(default=None, max_length=100, null=True)),
                ('other_qual', models.CharField(default=None, max_length=100, null=True)),
                ('dob', models.CharField(default=None, max_length=50, null=True)),
                ('Resume', models.CharField(default=None, max_length=100, null=True)),
                ('photo', models.CharField(default=None, max_length=200, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jobseeker',
            },
        ),
    ]
